# Generated by Django 3.0.8 on 2020-07-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0002_auto_20200722_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='close',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open',
            field=models.CharField(max_length=10),
        ),
    ]
