# Generated by Django 3.0.7 on 2020-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0007_auto_20200727_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish',
        ),
        migrations.AddField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(default=None, null=True, to='rab.Dish'),
        ),
    ]
