# Generated by Django 3.0.7 on 2020-07-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0008_auto_20200728_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish',
        ),
        migrations.AddField(
            model_name='menu',
            name='dish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rab.Dish'),
        ),
    ]
