# Generated by Django 3.0.7 on 2020-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0012_auto_20200729_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order_state',
            field=models.CharField(default='NO ORDER PLACED', max_length=50, unique=True),
        ),
    ]
