# Generated by Django 3.0.8 on 2020-08-02 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0015_menu_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
