# Generated by Django 3.0.7 on 2020-08-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0016_auto_20200802_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='serve',
            field=models.BooleanField(default=False),
        ),
    ]
