# Generated by Django 3.0.7 on 2020-08-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0017_auto_20200803_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='serve',
            field=models.IntegerField(default=0),
        ),
    ]
